### ISSUE TITLE
GitHub Actions run twice on PRs

### ISSUE THREAD

**Issue by bitlux** [bitlux/caches#38]
You probably want:
```
push:
  branches: [ "dev" ]
pull_request:
  branches: [ "master" ]
```
